language: python
python:
  - "2.7"
install:
  - pip install pygments
  - pip install lxml
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable bikeshed
  - bikeshed update
script:
  - bikeshed spec
